cart/urls.py
from django.urls import path
from .import views

app_name  = 'cart'

urlpatterns = [
    path('', views.cart_view, name='cart'),
    path('add/', views.addToCart, name='add'),
    path('delete/<int:product_id>/<int:qty>', views.delete_item, name='delete'),
    path('remove/', views.remove , name='remove'),
    path('order/add/<int:cart_id>', views.addOrder, name='order_add'),
    path('order/done/', views.orderDone, name='order_done'),
]

nikestore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
    path('accounts/', include('allauth.urls')),
    path('cart/', include('cart.urls', namespace='cart'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('',views.HomePageView.as_view() , name='home'),
    path('detail/<pk>',views.ProductDetailView.as_view(),name='product_detail'),

    path('category/<slug:category_slug>/', views.categoryDetail,name='category_detail'),
    path('tag/<slug:tag_slug>/', views.tagDetail,name='tag_detail'),

    path('accounts/profile/', views.profile, name='profile')
]

cart/models.py
from django.db import models
from shop.models import Product

# Create your models here.
class CartProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='cart_products')
    quantity = models.PositiveIntegerField(default=1)
    price = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.product.name)

    def get_total_price(self):
        cart_product_total_price = self.quantity * self.product.price
        return int(cart_product_total_price)

class Cart(models.Model):
    products = models.ManyToManyField(CartProduct)
    total_quantity = models.PositiveIntegerField(default=0)
    total_price = models.PositiveIntegerField(default=0)

    def add(self,product_id, qty):
        product = Product.objects.get(id=product_id)
        price = product.price * int(qty)
        self.products.create(
            product=product,
            quantity=qty,
            price=price,
            )
        self.total_quantity += int(qty)
        self.total_price += price
        self.save()
        return True

    def deleteItem(self, product_id, qty):
        product = Product.objects.get(id=product_id)
        p_id = product.id
        for item in self.products.all():
            if item.product.id == p_id:
                item.delete()
        price = product.price * int(qty)
        # self.products.remove(product)

        self.total_quantity -= qty
        self.total_price -= price
        self.save()
        return True

    def __str__(self):
        return f"{self.total_quantity}"


class OrderProduct(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_products')
    quantity = models.PositiveIntegerField(default=1)
    price = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.product.name)

class Order(models.Model):
    STATES = (
        ("Farg'ona","fergana"),
        ("Namangan","namangan"),
        ("Andijon","andijan"),
    )
    name = models.CharField('Ism-Sharifi', max_length=200)
    state = models.CharField('Viloyat', max_length=50, choices=STATES)
    address = models.CharField('Manzil', max_length=300)
    phone = models.CharField('Telefon',max_length=11 )
    products = models.ManyToManyField(OrderProduct)
    # order_sum = models.PositiveIntegerField('Narx',default=0)
    total_sum = models.PositiveIntegerField('Umumiy narx',default=0)
    payed = models.BooleanField(default=False)

    def __str__(self):
        return str(self.name)

cart/forms.py
from django import forms
from .models import *
class AddOrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'
        exclude = ['products','payed', 'total_sum']

cart/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from shop.models import Product
from .models import *
# Create your views here.
from .import forms

def cart_init(request):
    try:
        cart = Cart.objects.get(id=request.session.get('user_cart_id'))
    except:
        cart = Cart.objects.create()
        request.session['user_cart_id'] = cart.id
    return cart


def cart_view(request):
    item_counter = 0
    try:
        cart = Cart.objects.get(id=request.session.get('user_cart_id'))
    except:
        cart = {'notfound': "Products not found!"}
    return render(request,'cart/cart_view.html', {'cart':cart})

import json
def addToCart(request):
    d = request.GET.get('data')
    data = json.loads(d)
    cart = cart_init(request)
    cart.add(data['product_id'],data['count'])
    if cart:
        status = {
            'status':200
        }
    else:
        status = {
            'status': 200
        }
    return JsonResponse(status)

def delete_item(request, product_id, qty):
    cart = Cart.objects.get(id=request.session.get('user_cart_id'))
    cart.deleteItem(product_id, qty)

    return redirect('cart:cart')

def remove(request):
    print(request.path)
    try:
        cart = Cart.objects.get(id=request.session.get('user_cart_id'))
    except:
        return redirect('cart:cart')
    cart.delete()
    return redirect('cart:cart')

# Orders view
def addOrder(request, cart_id):
    item_counter = 0
    try:
        caart = Cart.objects.get(id=request.session.get('user_cart_id'))
    except:
        caart = {'notfound': "Products not found!"}
    cart = Cart.objects.get(id=cart_id)
    if request.method == 'POST':
        form = forms.AddOrderForm(request.POST)
        if form.is_valid():
            f = form.save()
            for p in cart.products.all():
                f.products.create(
                    product=p.product,
                    quantity=p.quantity,
                    price=p.quantity * p.price
                )
            f.payed = False
            f.total_sum = cart.total_price
            f.save()
            order = Order.objects.last()
            return render(request,'cart/order_done.html', {'order':order})
    else:
        form = forms.AddOrderForm()
    return render(request, 'cart/order.html', {'form':form, 'caart':caart})

def orderDone(request):
    return render(request, 'cart/order_done.html')

templates/cart/cart_view.html
{% extends 'wrapper.html' %}
{% load static %}
{% block content %}
  
  <main class="main-content">
    <!--== Start Page Title Area ==-->
    <section class="page-title-area">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-12 m-auto">
            <div class="page-title-content text-center">
              <h2 class="title">Cart</h2>
              <div class="bread-crumbs"><a href="index.html"> Home </a><span class="breadcrumb-sep"> // </span><span class="active"> Cart</span></div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--== End Page Title Area ==-->

    <!--== Start Cart Area Wrapper ==-->
    <section class="product-area cart-page-area">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 m-auto">
            <div class="section-title text-center">
              <h2 class="title">Cart</h2>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <div class="cart-table-wrap">
              <div class="cart-table table-responsive">
                <table>
                  <thead>
                    <tr>
                      <th class="width-thumbnail"></th>
                      <th class="width-name">Product</th>
                      <th class="width-price"> Price</th>
                      <th class="width-quantity">Quantity</th>
                      <th class="width-subtotal">Subtotal</th>
                      <th class="width-remove"></th>
                    </tr>
                  </thead>
                  <tbody>
                  {% for cart in cart.products.all %}
                    {% with cart as item %}
                    <tr>
                      <td class="product-thumbnail">
                        <a href="{% url 'shop:product_detail' item.product.id %}"><img src="{{item.product.image.url}}" alt="Image"></a>
                      </td>
                      <td class="product-name">
                        <h5><a href="shop-single-product.html">{{item.product.name}}</a></h5>
                      </td>
                      <td class="product-price"><span class="amount">${{item.product.price}}</span></td>
                      <td class="cart-quality">
                        <div class="product-details-quality">
                          <input type="number" class="input-text qty text" step="1" min="1" max="100" name="quantity" value="{{item.quantity}}" title="Qty" placeholder="">
                        </div>
                      </td>
                      <td class="product-total"><span>${{item.get_total_price}}</span></td>
                      <td class="product-remove"><a href="{% url 'cart:delete' item.product.id item.quantity  %}"><i class="ion-ios-trash-outline"></i></a></td>
                    </tr>
                    {% endwith %}
                  {% endfor %}
                </tbody>
              </table>
              </div>
            </div>
            <div class="cart-shiping-update-wrapper">
              <div class="cart-shiping-btn continure-btn">
                <a class="btn btn-link" href="{% url 'shop:home' %}"><i class="ion-ios-arrow-left"></i> Back To Shop</a>
              </div>
              <div class="cart-shiping-btn update-btn">
                <a class="btn btn-link" href="{% url 'cart:order_add' cart.id %}"><i class="ion-ios-reload"></i> Go To Order</a>
              </div>
            </div>
          </div>
          <div class="col-lg-4">
          </div>
        </div>
      </div>
    </section>
    <!--== End Cart Area Wrapper ==-->
  </main>

{% endblock %}

templates/cart/order.html
{% extends 'wrapper.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
  
  <main class="main-content">
    <!--== Start Page Title Area ==-->
    <section class="page-title-area">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-lg-12 m-auto">
            <div class="page-title-content text-center">
              <h2 class="title">Buyurtma</h2>
              <div class="bread-crumbs"><a href="index.html"> Bosh Sahifa </a><span class="breadcrumb-sep"> // </span><span class="active"> Buyurtma</span></div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--== End Page Title Area ==-->

    <!--== Start Checkout Area Wrapper ==-->
    <section class="product-area shop-checkout-area">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 m-auto">
            <div class="section-title text-center">
              <h2 class="title">Buyurtma</h2>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-7">
            <div class="billing-info-wrap">
              <h3>Malumotlarni Kiriting</h3>
              <div class="row">
                <form action="" method="POST">
                  {% csrf_token %}
                  {{form|crispy}}
                  <center>
                    <input type="submit" class="btn btn-primary btn-lg" value="Tasdiqlash">
                  </center>
                </form>
              </div>
            </div>
          </div>
          <div class="col-lg-5">
            <div class="your-order-area">
              {% block title %} "{{ request.user.username }}" ning savatchasi {% endblock %}
              <div class="your-order-wrap">
                <div class="your-order-info-wrap">
                  <div class="your-order-title">
                    <h4>Product <span>Subtotal</span></h4>
                  </div>
                  <div class="your-order-product">
                    <ul>
                      {% for cart in caart.products.all %}
                      {% with cart as item %}
                      <li>{{item.product.name}} ---× {{item.quantity}} <span>${{item.get_total_price}} </span></li>
                      {% endwith %}
                      {% endfor %}
                    </ul>
                  </div>
                  <div class="your-order-subtotal">
                    <h3>Subtotal <span>${{ cart.total_price }}</span></h3>
                  </div>                
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--== End Checkout Area Wrapper ==-->
  </main>

{% endblock %}

templates/cart/order_done.html
{% extends '../wrapper.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    {% block title %} <title>Savatcha | {{ request.user.username }}</title>{% endblock %}
<div class="adminx-content">
<div class="adminx-main-content">
  <div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-12">
            <div class="card p-5">
                <div class="card-header">
                    <h2>Buyurtma barildi !</h2>
                </div>
               <div class="row">
                   <div class="col-sm-6">
                        <div class="mt-2">
                            <ul>
                                <li>Buyurtmachi : <strong>{{ order.name }}</strong>   </li>
                                <li>Viloyat : <strong>{{ order.state }}</strong></li>
                                <li>Manzil : <strong>{{ order.address }}</strong></li>
                                <li>Telefon : <strong>{{ order.phone }}</strong></li>
                                <li>Umumiy summa : <strong>${{ order.total_sum }}</strong></li>
                            </ul>

                        </div>
                   </div>
                   <div class="col-sm-6">
                       <ul class="list-unstyled">
                           {% for product in order.products.all %}
                               <br>
                             <li class="d-block">
                                 <img src="{{ product.product.image.url }}"
                                      width="50"
                                      style="float:left; margin-top: 10px;" alt="">
                                 <h5 style="margin-left:20px;">{{ product.product.name }}</h5>
                             </li>
                               <br>
                           {% endfor %}
                       </ul>
                       <br>
                       <a href="/" class="btn btn-primary">
                           Bosh sahifa
                       </a>
                   </div>
               </div>
            </div>


        </div>
    </div>
  </div>
</div>
</div>

{% endblock %}